# Generated by Django 5.1.4 on 2025-01-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_link_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('review', 'Review'), ('booking', 'Booking'), ('payment', 'Payment'), ('amenity', 'Amenity'), ('general', 'General')], max_length=50),
        ),
    ]
