# Generated by Django 5.1.4 on 2025-01-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_category',
            field=models.CharField(choices=[('review', 'Review'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('payment_received', 'Payment Received'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('amenity_added', 'Amenity Added'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'INFO'), ('warning', 'WARNING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='info', max_length=50),
        ),
    ]
