# Generated by Django 5.1.4 on 2025-01-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_notification_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_category',
            field=models.CharField(choices=[('review', 'Review'), ('booking_received', 'Booking Received'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('payment_received', 'Payment Received'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('amenity_added', 'Amenity Added'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
