# Generated by Django 5.1.4 on 2025-02-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_category',
            field=models.CharField(choices=[('review', 'Review'), ('booking_received', 'Booking Received'), ('booking_accepted', 'Booking Accepted'), ('booking_rejected', 'Booking Rejected'), ('payment_received', 'Payment Received'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_pending', 'Payment Pending'), ('amenity_added', 'Amenity Added'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
