# Generated by Django 5.1.4 on 2025-01-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter a unique name for the amenity (e.g., 'Pool').", max_length=30, unique=True)),
                ('description', models.TextField(help_text='Provide a brief description of the amenity.', null=True)),
            ],
            options={
                'verbose_name': 'amenity',
                'verbose_name_plural': 'amenities',
                'ordering': ['name'],
            },
        ),
    ]
