# Generated by Django 5.1.4 on 2025-02-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a brief description of the amenity.', null=True),
        ),
    ]
