# Generated by Django 5.1.4 on 2025-01-09 23:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amenities', '0001_initial'),
        ('location', '0003_alter_continent_id_alter_country_id_alter_state_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text="Enter the name of the property (e.g., 'Sunset Villa').", max_length=255)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_guests', models.IntegerField(default=5)),
                ('bathrooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('categories', models.CharField(max_length=25)),
                ('beds', models.IntegerField()),
                ('pets_allowed', models.BooleanField(default=False)),
                ('parking_space', models.BooleanField(default=False)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, help_text='Discount as a percentage (e.g., 20 for 20%).', max_digits=5, null=True)),
                ('cleaning_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(help_text='Specify the address of the property.', on_delete=django.db.models.deletion.CASCADE, related_name='property', to='location.address')),
                ('amenities', models.ManyToManyField(blank=True, help_text='Select the amenities available for this property.', related_name='properties', to='amenities.amenity')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['name'],
            },
        ),
    ]
