# Generated by Django 5.1.4 on 2025-01-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='booking_type',
            field=models.CharField(choices=[('instant', 'INSTANT'), ('booking', 'BOOKING')], db_default='instant', default='instant', help_text='The type of booking that this property has', max_length=20),
        ),
    ]
