# Generated by Django 5.1.4 on 2025-01-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_properties_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='max_guests',
            field=models.IntegerField(db_default=5, default=5),
        ),
    ]
