import type { Metadata } from "next";
import { manRope } from "./utils/font";
import "./globals.css";
import Navbar from "./ui/navbar";
import Footer from "./ui/footer";

import AppContextProvider from "./utils/context";
import AuthDisplay from "./ui/authentication/auth-display";

export const metadata: Metadata = {
  title: {
    template: "%s | Airbnb",
    default: "Vacation Rentals, Cabins, Bseach",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" >
      <AppContextProvider>
        <body className={`${manRope.className}   text-black antialiased    `}
        >
          <div className={`max-w-[150rem] mx-auto px-6  `}>
          <Navbar />
          <AuthDisplay />
          {children}
          </div>
          
          <Footer />
        </body>
      </AppContextProvider>
    </html>
  );
}
