import type { Metadata } from "next";
import { manRope } from "./utilities/font";
import "./globals.css";
import Navbar from "./ui/navbar";
import Footer from "./ui/footer";
import ReduxProvider from "../store/provider";

import ModalProvider from "./utilities/context";
import Modals from "../components/modals/modals";
import NextQueryProvider from "./queryclient";

import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: {
    template: "%s | Airbnb",
    default: "Vacation Rentals, Cabins, Bseach",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <ModalProvider>
          <body className={`${manRope.className}   text-black antialiased    `}>
            <NextQueryProvider>
              <div className={`max-w-[150rem] mx-auto px-6  `}>
                <Navbar />
                {children}
              </div>

              <Footer />
              <Modals />
              <ToastContainer />
            </NextQueryProvider>
          </body>
        </ModalProvider>
      </ReduxProvider>
    </html>
  );
}
