import type { Metadata } from "next";
import { manRope } from "./utils/font";
import "./globals.css";
import Navbar from "./ui/navbar";
import Footer from "./ui/footer";
import ReduxProvider from "./redux/provider";

import ModalProvider from "./utils/context";
import Modals from "./customComponents/modals/modals";

export const metadata: Metadata = {
  title: {
    template: "%s | Airbnb",
    default: "Vacation Rentals, Cabins, Bseach",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <ModalProvider>
          <body className={`${manRope.className}   text-black antialiased    `}>
            <div className={`max-w-[150rem] mx-auto px-6  `}>
              <Navbar />
              {children}
            </div>

            <Footer />
            <Modals />
          </body>
        </ModalProvider>
      </ReduxProvider>
    </html>
  );
}
