# Generated by Django 5.1.4 on 2025-02-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_bankingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankingdetails',
            name='account_number_hash',
            field=models.CharField(max_length=68, unique=True),
        ),
    ]
