import sys

from django.core.management import BaseCommand
from django.core.exceptions import ValidationError
from ...models import Continent, Country


african_countries = {
    "Africa":  [
    {"country": "Algeria", "calling_code": "+213"},
    {"country": "Angola", "calling_code": "+244"},
    {"country": "Benin", "calling_code": "+229"},
    {"country": "Botswana", "calling_code": "+267"},
    {"country": "Burkina Faso", "calling_code": "+226"},
    {"country": "Burundi", "calling_code": "+257"},
    {"country": "Cape Verde", "calling_code": "+238"},
    {"country": "Cameroon", "calling_code": "+237"},
    {"country": "Central African Republic", "calling_code": "+236"},
    {"country": "Chad", "calling_code": "+235"},
    {"country": "Comoros", "calling_code": "+269"},
    {"country": "Congo, Democratic Republic of", "calling_code": "+243"},
    {"country": "Congo, Republic of", "calling_code": "+242"},
    {"country": "Djibouti", "calling_code": "+253"},
    {"country": "Egypt", "calling_code": "+20"},
    {"country": "Equatorial Guinea", "calling_code": "+240"},
    {"country": "Eritrea", "calling_code": "+291"},
    {"country": "Eswatini (Swaziland)", "calling_code": "+268"},
    {"country": "Ethiopia", "calling_code": "+251"},
    {"country": "Gabon", "calling_code": "+241"},
    {"country": "Gambia", "calling_code": "+220"},
    {"country": "Ghana", "calling_code": "+233"},
    {"country": "Guinea", "calling_code": "+224"},
    {"country": "Guinea-Bissau", "calling_code": "+245"},
    {"country": "Ivory Coast (Côte d'Ivoire)", "calling_code": "+225"},
    {"country": "Kenya", "calling_code": "+254"},
    {"country": "Lesotho", "calling_code": "+266"},
    {"country": "Liberia", "calling_code": "+231"},
    {"country": "Libya", "calling_code": "+218"},
    {"country": "Madagascar", "calling_code": "+261"},
    {"country": "Malawi", "calling_code": "+265"},
    {"country": "Mali", "calling_code": "+223"},
    {"country": "Mauritania", "calling_code": "+222"},
    {"country": "Mauritius", "calling_code": "+230"},
    {"country": "Morocco", "calling_code": "+212"},
    {"country": "Mozambique", "calling_code": "+258"},
    {"country": "Namibia", "calling_code": "+264"},
    {"country": "Niger", "calling_code": "+227"},
    {"country": "Nigeria", "calling_code": "+234"},
    {"country": "Rwanda", "calling_code": "+250"},
    {"country": "Sao Tome and Principe", "calling_code": "+239"},
    {"country": "Senegal", "calling_code": "+221"},
    {"country": "Seychelles", "calling_code": "+248"},
    {"country": "Sierra Leone", "calling_code": "+232"},
    {"country": "Somalia", "calling_code": "+252"},
    {"country": "South Africa", "calling_code": "+27"},
    {"country": "South Sudan", "calling_code": "+211"},
    {"country": "Sudan", "calling_code": "+249"},
    {"country": "Tanzania", "calling_code": "+255"},
    {"country": "Togo", "calling_code": "+228"},
    {"country": "Tunisia", "calling_code": "+216"},
    {"country": "Uganda", "calling_code": "+256"},
    {"country": "Zambia", "calling_code": "+260"},
    {"country": "Zimbabwe", "calling_code": "+263"}
],
    "Europe": [
        {"country": "Albania", "calling_code": "+355"},
        {"country": "Andorra", "calling_code": "+376"},
        {"country": "Armenia", "calling_code": "+374"},
        {"country": "Austria", "calling_code": "+43"},
        {"country": "Azerbaijan", "calling_code": "+994"},
        {"country": "Belarus", "calling_code": "+375"},
        {"country": "Belgium", "calling_code": "+32"},
        {"country": "Bosnia and Herzegovina", "calling_code": "+387"},
        {"country": "Bulgaria", "calling_code": "+359"},
        {"country": "Croatia", "calling_code": "+385"},
        {"country": "Cyprus", "calling_code": "+357"},
        {"country": "Czech Republic", "calling_code": "+420"},
        {"country": "Denmark", "calling_code": "+45"},
        {"country": "Estonia", "calling_code": "+372"},
        {"country": "Finland", "calling_code": "+358"},
        {"country": "France", "calling_code": "+33"},
        {"country": "Georgia", "calling_code": "+995"},
        {"country": "Germany", "calling_code": "+49"},
        {"country": "Greece", "calling_code": "+30"},
        {"country": "Hungary", "calling_code": "+36"},
        {"country": "Iceland", "calling_code": "+354"},
        {"country": "Ireland", "calling_code": "+353"},
        {"country": "Italy", "calling_code": "+39"},
        {"country": "Kazakhstan", "calling_code": "+7"},
        {"country": "Kosovo", "calling_code": "+383"},
        {"country": "Latvia", "calling_code": "+371"},
        {"country": "Liechtenstein", "calling_code": "+423"},
        {"country": "Lithuania", "calling_code": "+370"},
        {"country": "Luxembourg", "calling_code": "+352"},
        {"country": "Malta", "calling_code": "+356"},
        {"country": "Moldova", "calling_code": "+373"},
        {"country": "Monaco", "calling_code": "+377"},
        {"country": "Montenegro", "calling_code": "+382"},
        {"country": "Netherlands", "calling_code": "+31"},
        {"country": "North Macedonia", "calling_code": "+389"},
        {"country": "Norway", "calling_code": "+47"},
        {"country": "Poland", "calling_code": "+48"},
        {"country": "Portugal", "calling_code": "+351"},
        {"country": "Romania", "calling_code": "+40"},
        {"country": "Russia", "calling_code": "+7"},
        {"country": "San Marino", "calling_code": "+378"},
        {"country": "Serbia", "calling_code": "+381"},
        {"country": "Slovakia", "calling_code": "+421"},
        {"country": "Slovenia", "calling_code": "+386"},
        {"country": "Spain", "calling_code": "+34"},
        {"country": "Sweden", "calling_code": "+46"},
        {"country": "Switzerland", "calling_code": "+41"},
        {"country": "Turkey", "calling_code": "+90"},
        {"country": "Ukraine", "calling_code": "+380"},
        {"country": "United Kingdom", "calling_code": "+44"},
        {"country": "Vatican City", "calling_code": "+379"},
    ],
"Asia": [
        {"country": "Afghanistan", "calling_code": "+93"},
        {"country": "Armenia", "calling_code": "+374"},
        {"country": "Azerbaijan", "calling_code": "+994"},
        {"country": "Bahrain", "calling_code": "+973"},
        {"country": "Bangladesh", "calling_code": "+880"},
        {"country": "Bhutan", "calling_code": "+975"},
        {"country": "Brunei", "calling_code": "+673"},
        {"country": "Cambodia", "calling_code": "+855"},
        {"country": "China", "calling_code": "+86"},
        {"country": "Cyprus", "calling_code": "+357"},
        {"country": "Georgia", "calling_code": "+995"},
        {"country": "India", "calling_code": "+91"},
        {"country": "Indonesia", "calling_code": "+62"},
        {"country": "Iran", "calling_code": "+98"},
        {"country": "Iraq", "calling_code": "+964"},
        {"country": "Israel", "calling_code": "+972"},
        {"country": "Japan", "calling_code": "+81"},
        {"country": "Jordan", "calling_code": "+962"},
        {"country": "Kazakhstan", "calling_code": "+7"},
        {"country": "Kuwait", "calling_code": "+965"},
        {"country": "Kyrgyzstan", "calling_code": "+996"},
        {"country": "Laos", "calling_code": "+856"},
        {"country": "Lebanon", "calling_code": "+961"},
        {"country": "Malaysia", "calling_code": "+60"},
        {"country": "Maldives", "calling_code": "+960"},
        {"country": "Mongolia", "calling_code": "+976"},
        {"country": "Myanmar", "calling_code": "+95"},
        {"country": "Nepal", "calling_code": "+977"},
        {"country": "North Korea", "calling_code": "+850"},
        {"country": "Oman", "calling_code": "+968"},
        {"country": "Pakistan", "calling_code": "+92"},
        {"country": "Palestine", "calling_code": "+970"},
        {"country": "Philippines", "calling_code": "+63"},
        {"country": "Qatar", "calling_code": "+974"},
        {"country": "Russia", "calling_code": "+7"},
        {"country": "Saudi Arabia", "calling_code": "+966"},
        {"country": "Singapore", "calling_code": "+65"},
        {"country": "South Korea", "calling_code": "+82"},
        {"country": "Sri Lanka", "calling_code": "+94"},
        {"country": "Syria", "calling_code": "+963"},
        {"country": "Tajikistan", "calling_code": "+992"},
        {"country": "Thailand", "calling_code": "+66"},
        {"country": "Timor-Leste", "calling_code": "+670"},
        {"country": "Turkey", "calling_code": "+90"},
        {"country": "Turkmenistan", "calling_code": "+993"},
        {"country": "United Arab Emirates", "calling_code": "+971"},
        {"country": "Uzbekistan", "calling_code": "+998"},
        {"country": "Vietnam", "calling_code": "+84"},
        {"country": "Yemen", "calling_code": "+967"}
    ],
    "North America": [
        {"country": "Antigua and Barbuda", "calling_code": "+1-268"},
        {"country": "Bahamas", "calling_code": "+1-242"},
        {"country": "Barbados", "calling_code": "+1-246"},
        {"country": "Belize", "calling_code": "+501"},
        {"country": "Canada", "calling_code": "+1"},
        {"country": "Costa Rica", "calling_code": "+506"},
        {"country": "Cuba", "calling_code": "+53"},
        {"country": "Dominica", "calling_code": "+1-767"},
        {"country": "Dominican Republic", "calling_code": "+1-809"},
        {"country": "El Salvador", "calling_code": "+503"},
        {"country": "Grenada", "calling_code": "+1-473"},
        {"country": "Guatemala", "calling_code": "+502"},
        {"country": "Haiti", "calling_code": "+509"},
        {"country": "Honduras", "calling_code": "+504"},
        {"country": "Jamaica", "calling_code": "+1-876"},
        {"country": "Mexico", "calling_code": "+52"},
        {"country": "Nicaragua", "calling_code": "+505"},
        {"country": "Panama", "calling_code": "+507"},
        {"country": "Saint Kitts and Nevis", "calling_code": "+1-869"},
        {"country": "Saint Lucia", "calling_code": "+1-758"},
        {"country": "Saint Vincent and the Grenadines", "calling_code": "+1-784"},
        {"country": "Trinidad and Tobago", "calling_code": "+1-868"},
        {"country": "United States", "calling_code": "+1"}
    ],
    "South America": [
        {"country": "Argentina", "calling_code": "+54"},
        {"country": "Bolivia", "calling_code": "+591"},
        {"country": "Brazil", "calling_code": "+55"},
        {"country": "Chile", "calling_code": "+56"},
        {"country": "Colombia", "calling_code": "+57"},
        {"country": "Ecuador", "calling_code": "+593"},
        {"country": "Guyana", "calling_code": "+592"},
        {"country": "Paraguay", "calling_code": "+595"},
        {"country": "Peru", "calling_code": "+51"},
        {"country": "Suriname", "calling_code": "+597"},
        {"country": "Uruguay", "calling_code": "+598"},
        {"country": "Venezuela", "calling_code": "+58"}
    ]
}

class Command(BaseCommand):

    def handle(self, *args, **options):
        """ custom command to execute adding countries to the DB """
        for key, value in african_countries.items():
            continent_instance, created = Continent.objects.get_or_create(
                name=key)
            for country in value:
                instance, created = Country.objects.get_or_create(
                    name=country['country'],
                                   dialing_code=country['calling_code'],
                                   continent=continent_instance)
                if instance:
                    print(f"{country['country']} already exists")
                else:
                    print(f"{country['country']} successfully created")
            self.stdout.write(
            self.style.SUCCESS("Countries added successfully!"))
