# Generated by Django 5.1.4 on 2025-01-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_country_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='dialing_code',
            field=models.CharField(max_length=7),
        ),
    ]
