# Generated by Django 5.1.4 on 2025-01-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_continent_name_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('name', 'dialing_code', 'continent')},
        ),
    ]
