# Generated by Django 5.1.4 on 2025-01-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_country_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
