# Generated by Django 5.1.4 on 2025-01-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
