# Generated by Django 5.1.4 on 2025-01-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_address', to='location.town'),
        ),
    ]
