# Generated by Django 5.1.4 on 2025-01-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_alter_address_town'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
